<?php

use App\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Country::insert([
            ['phone_code' => '93' , 'title' => 'Afghanistan'],
            ['phone_code' =>'355' , 'title' => 'Albania'],
            ['phone_code' =>'213' , 'title' => 'Algeria'],
            ['phone_code' =>'684' , 'title' => 'American Samoa'],
            ['phone_code' =>'376' , 'title' => 'Andorra'],
            ['phone_code' =>'244' , 'title' => 'Angola'],
            ['phone_code' =>'809' , 'title' => 'Anguilla'],
            ['phone_code' =>'268' , 'title' => 'Antigua'],
            ['phone_code' =>'54' , 'title' => 'Argentina'],
            ['phone_code' =>'374' , 'title' => 'Armenia'],
            ['phone_code' =>'297' , 'title' => 'Aruba'],
            ['phone_code' =>'247' , 'title' => 'Ascension Island'],
            ['phone_code' =>'61' , 'title' => 'Australia'],
            ['phone_code' =>'672' , 'title' => 'Australian External Territories'],
            ['phone_code' =>'43' , 'title' => 'Austria'],
            ['phone_code' =>'994' , 'title' => 'Azerbaijan'],
            ['phone_code' =>'242' , 'title' => 'Bahamas'],
            ['phone_code' =>'246' , 'title' => 'Barbados'],
            ['phone_code' =>'973' , 'title' => 'Bahrain'],
            ['phone_code' =>'880' , 'title' => 'Bangladesh'],
            ['phone_code' =>'375' , 'title' => 'Belarus'],
            ['phone_code' =>'32' , 'title' => 'Belgium'],
            ['phone_code' =>'501' , 'title' => 'Belize'],
            ['phone_code' =>'229' , 'title' => 'Benin'],
            ['phone_code' =>'809' , 'title' => 'Bermuda'],
            ['phone_code' =>'975' , 'title' => 'Bhutan'],
            ['phone_code' =>'284' , 'title' => 'British Virgin Islands'],
            ['phone_code' =>'591' , 'title' => 'Bolivia'],
            ['phone_code' =>'387' , 'title' => 'Bosnia and Hercegovina'],
            ['phone_code' =>'267' , 'title' => 'Botswana'],
            ['phone_code' =>'55' , 'title' => 'Brazil'],
            ['phone_code' =>'284' , 'title' => 'British V.I.'],
            ['phone_code' =>'673' , 'title' => 'Brunei Darussalm'],
            ['phone_code' =>'359' , 'title' => 'Bulgaria'],
            ['phone_code' =>'226' , 'title' => 'Burkina Faso'],
            ['phone_code' =>'257' , 'title' => 'Burundi'],
            ['phone_code' =>'855' , 'title' => 'Cambodia'],
            ['phone_code' =>'237' , 'title' => 'Cameroon'],
            ['phone_code' =>'1' , 'title' => 'Canada'],
            ['phone_code' =>'238' , 'title' => 'CapeVerde Islands'],
            ['phone_code' =>'1' , 'title' => 'Caribbean Nations'],
            ['phone_code' =>'345' , 'title' => 'Cayman Islands'],
            ['phone_code' =>'238' , 'title' => 'Cape Verdi'],
            ['phone_code' =>'236' , 'title' => 'Central African Republic'],
            ['phone_code' =>'235' , 'title' => 'Chad'],
            ['phone_code' =>'56' , 'title' => 'Chile'],
            ['phone_code' =>'86' , 'title' => 'China (People\'s Republic)'],
            ['phone_code' =>'886' , 'title' => 'China-Taiwan'],
            ['phone_code' =>'57' , 'title' => 'Colombia'],
            ['phone_code' =>'269' , 'title' => 'Comoros and Mayotte'],
            ['phone_code' =>'242' , 'title' => 'Congo'],
            ['phone_code' =>'682' , 'title' => 'Cook Islands'],
            ['phone_code' =>'506' , 'title' => 'Costa Rica'],
            ['phone_code' =>'385' , 'title' => 'Croatia'],
            ['phone_code' =>'53' , 'title' => 'Cuba'],
            ['phone_code' =>'357' , 'title' => 'Cyprus'],
            ['phone_code' =>'420' , 'title' => 'Czech Republic'],
            ['phone_code' =>'45' , 'title' => 'Denmark'],
            ['phone_code' =>'246' , 'title' => 'Diego Garcia'],
            ['phone_code' =>'767' , 'title' => 'Dominca'],
            ['phone_code' =>'809' , 'title' => 'Dominican Republic'],
            ['phone_code' =>'253' , 'title' => 'Djibouti'],
            ['phone_code' =>'593' , 'title' => 'Ecuador'],
            ['phone_code' =>'20' , 'title' => 'Egypt'],
            ['phone_code' =>'503' , 'title' => 'El Salvador'],
            ['phone_code' =>'240' , 'title' => 'Equatorial Guinea'],
            ['phone_code' =>'291' , 'title' => 'Eritrea'],
            ['phone_code' =>'372' , 'title' => 'Estonia'],
            ['phone_code' =>'251' , 'title' => 'Ethiopia'],
            ['phone_code' =>'500' , 'title' => 'Falkland Islands'],
            ['phone_code' =>'298' , 'title' => 'Faroe (Faeroe) Islands (Denmark)'],
            ['phone_code' =>'679' , 'title' => 'Fiji'],
            ['phone_code' =>'358' , 'title' => 'Finland'],
            ['phone_code' =>'33' , 'title' => 'France'],
            ['phone_code' =>'596' , 'title' => 'French Antilles'],
            ['phone_code' =>'594' , 'title' => 'French Guiana'],
            ['phone_code' =>'241' , 'title' => 'Gabon (Gabonese Republic)'],
            ['phone_code' =>'220' , 'title' => 'Gambia'],
            ['phone_code' =>'995' , 'title' => 'Georgia'],
            ['phone_code' =>'49' , 'title' => 'Germany'],
            ['phone_code' =>'233' , 'title' => 'Ghana'],
            ['phone_code' =>'350' , 'title' => 'Gibraltar'],
            ['phone_code' =>'30' , 'title' => 'Greece'],
            ['phone_code' =>'299' , 'title' => 'Greenland'],
            ['phone_code' =>'473' , 'title' => 'Grenada/Carricou'],
            ['phone_code' =>'671' , 'title' => 'Guam'],
            ['phone_code' =>'502' , 'title' => 'Guatemala'],
            ['phone_code' =>'224' , 'title' => 'Guinea'],
            ['phone_code' =>'245' , 'title' => 'Guinea-Bissau'],
            ['phone_code' =>'592' , 'title' => 'Guyana'],
            ['phone_code' =>'509' , 'title' => 'Haiti'],
            ['phone_code' =>'504' , 'title' => 'Honduras'],
            ['phone_code' =>'852' , 'title' => 'Hong Kong'],
            ['phone_code' =>'36' , 'title' => 'Hungary'],
            ['phone_code' =>'354' , 'title' => 'Iceland'],
            ['phone_code' =>'91' , 'title' => 'India'],
            ['phone_code' =>'62' , 'title' => 'Indonesia'],
            ['phone_code' =>'98' , 'title' => 'Iran'],
            ['phone_code' =>'964' , 'title' => 'Iraq'],
            ['phone_code' =>'353' , 'title' => 'Ireland (Irish Republic; Eire)'],
            ['phone_code' =>'972' , 'title' => 'Israel'],
            ['phone_code' =>'39' , 'title' => 'Italy'],
            ['phone_code' =>'225' , 'title' => 'Ivory Coast (La Cote d\'Ivoire)'],
            ['phone_code' =>'876' , 'title' => 'Jamaica'],
            ['phone_code' =>'81' , 'title' => 'Japan'],
            ['phone_code' =>'962' , 'title' => 'Jordan'],
            ['phone_code' =>'7' , 'title' => 'Kazakhstan'],
            ['phone_code' =>'254' , 'title' => 'Kenya'],
            ['phone_code' =>'855' , 'title' => 'Khmer Republic (Cambodia/Kampuchea)'],
            ['phone_code' =>'686' , 'title' => 'Kiribati Republic (Gilbert Islands)'],
            ['phone_code' =>'82' , 'title' => 'Korea, Republic of (South Korea)'],
            ['phone_code' =>'850' , 'title' => 'Korea, People\'s Republic of (North Korea)'],
            ['phone_code' =>'965' , 'title' => 'Kuwait'],
            ['phone_code' =>'996' , 'title' => 'Kyrgyz Republic'],
            ['phone_code' =>'371' , 'title' => 'Latvia'],
            ['phone_code' =>'856' , 'title' => 'Laos'],
            ['phone_code' =>'961' , 'title' => 'Lebanon'],
            ['phone_code' =>'266' , 'title' => 'Lesotho'],
            ['phone_code' =>'231' , 'title' => 'Liberia'],
            ['phone_code' =>'370' , 'title' => 'Lithuania'],
            ['phone_code' =>'218' , 'title' => 'Libya'],
            ['phone_code' =>'423' , 'title' => 'Liechtenstein'],
            ['phone_code' =>'352' , 'title' => 'Luxembourg'],
            ['phone_code' =>'853' , 'title' => 'Macao'],
            ['phone_code' =>'389' , 'title' => 'Macedonia'],
            ['phone_code' =>'261' , 'title' => 'Madagascar'],
            ['phone_code' =>'265' , 'title' => 'Malawi'],
            ['phone_code' =>'60' , 'title' => 'Malaysia'],
            ['phone_code' =>'960' , 'title' => 'Maldives'],
            ['phone_code' =>'223' , 'title' => 'Mali'],
            ['phone_code' =>'356' , 'title' => 'Malta'],
            ['phone_code' =>'692' , 'title' => 'Marshall Islands'],
            ['phone_code' =>'596' , 'title' => 'Martinique (French Antilles)'],
            ['phone_code' =>'222' , 'title' => 'Mauritania'],
            ['phone_code' =>'230' , 'title' => 'Mauritius'],
            ['phone_code' =>'269' , 'title' => 'Mayolte'],
            ['phone_code' =>'52' , 'title' => 'Mexico'],
            ['phone_code' =>'691' , 'title' => 'Micronesia (F.S. of Polynesia)'],
            ['phone_code' =>'373' , 'title' => 'Moldova'],
            ['phone_code' =>'33' , 'title' => 'Monaco'],
            ['phone_code' =>'976' , 'title' => 'Mongolia'],
            ['phone_code' =>'382' , 'title' => 'Montenegro'],
            ['phone_code' =>'473' , 'title' => 'Montserrat'],
            ['phone_code' =>'212' , 'title' => 'Morocco'],
            ['phone_code' =>'258' , 'title' => 'Mozambique'],
            ['phone_code' =>'95' , 'title' => 'Myanmar (former Burma)'],
            ['phone_code' =>'264' , 'title' => 'Namibia (former South-West Africa)'],
            ['phone_code' =>'674' , 'title' => 'Nauru'],
            ['phone_code' =>'977' , 'title' => 'Nepal'],
            ['phone_code' =>'31' , 'title' => 'Netherlands'],
            ['phone_code' =>'599' , 'title' => 'Netherlands Antilles'],
            ['phone_code' =>'869' , 'title' => 'Nevis'],
            ['phone_code' =>'687' , 'title' => 'New Caledonia'],
            ['phone_code' =>'64' , 'title' => 'New Zealand'],
            ['phone_code' =>'505' , 'title' => 'Nicaragua'],
            ['phone_code' =>'227' , 'title' => 'Niger'],
            ['phone_code' =>'234' , 'title' => 'Nigeria'],
            ['phone_code' =>'683' , 'title' => 'Niue'],
            ['phone_code' =>'850' , 'title' => 'North Korea'],
            ['phone_code' =>'1 670' , 'title' => 'North Mariana Islands (Saipan)'],
            ['phone_code' =>'47' , 'title' => 'Norway'],
            ['phone_code' =>'968' , 'title' => 'Oman'],
            ['phone_code' =>'92' , 'title' => 'Pakistan'],
            ['phone_code' =>'680' , 'title' => 'Palau'],
            ['phone_code' =>'507' , 'title' => 'Panama'],
            ['phone_code' =>'675' , 'title' => 'Papua New Guinea'],
            ['phone_code' =>'595' , 'title' => 'Paraguay'],
            ['phone_code' =>'51' , 'title' => 'Peru'],
            ['phone_code' =>'63' , 'title' => 'Philippines'],
            ['phone_code' =>'48' , 'title' => 'Poland'],
            ['phone_code' =>'351' , 'title' => 'Portugal (includes Azores)'],
            ['phone_code' =>'1 787' , 'title' => 'Puerto Rico'],
            ['phone_code' =>'974' , 'title' => 'Qatar'],
            ['phone_code' =>'262' , 'title' => 'Reunion (France)'],
            ['phone_code' =>'40' , 'title' => 'Romania'],
            ['phone_code' =>'7' , 'title' => 'Russia'],
            ['phone_code' =>'250' , 'title' => 'Rwanda (Rwandese Republic)'],
            ['phone_code' =>'670' , 'title' => 'Saipan'],
            ['phone_code' =>'378' , 'title' => 'San Marino'],
            ['phone_code' =>'239' , 'title' => 'Sao Tome and Principe'],
            ['phone_code' =>'966' , 'title' => 'Saudi Arabia'],
            ['phone_code' =>'221' , 'title' => 'Senegal'],
            ['phone_code' =>'381' , 'title' => 'Serbia'],
            ['phone_code' =>'248' , 'title' => 'Seychelles'],
            ['phone_code' =>'232' , 'title' => 'Sierra Leone'],
            ['phone_code' =>'65' , 'title' => 'Singapore'],
            ['phone_code' =>'421' , 'title' => 'Slovakia'],
            ['phone_code' =>'386' , 'title' => 'Slovenia'],
            ['phone_code' =>'677' , 'title' => 'Solomon Islands'],
            ['phone_code' =>'252' , 'title' => 'Somalia'],
            ['phone_code' =>'27' , 'title' => 'South Africa'],
            ['phone_code' =>'34' , 'title' => 'Spain'],
            ['phone_code' =>'94' , 'title' => 'Sri Lanka'],
            ['phone_code' =>'290' , 'title' => 'St. Helena'],
            ['phone_code' =>'869' , 'title' => 'St. Kitts/Nevis'],
            ['phone_code' =>'508' , 'title' => 'St. Pierre &(et) Miquelon (France)'],
            ['phone_code' =>'249' , 'title' => 'Sudan'],
            ['phone_code' =>'597' , 'title' => 'Suriname'],
            ['phone_code' =>'268' , 'title' => 'Swaziland'],
            ['phone_code' =>'46' , 'title' => 'Sweden'],
            ['phone_code' =>'41' , 'title' => 'Switzerland'],
            ['phone_code' =>'963' , 'title' => 'Syrian Arab Republic (Syria)'],
            ['phone_code' =>'689' , 'title' => 'Tahiti (French Polynesia)'],
            ['phone_code' =>'886' , 'title' => 'Taiwan'],
            ['phone_code' =>'7' , 'title' => 'Tajikistan'],
            ['phone_code' =>'255' , 'title' => 'Tanzania (includes Zanzibar)'],
            ['phone_code' =>'66' , 'title' => 'Thailand'],
            ['phone_code' =>'228' , 'title' => 'Togo (Togolese Republic)'],
            ['phone_code' =>'690' , 'title' => 'Tokelau'],
            ['phone_code' =>'676' , 'title' => 'Tonga'],
            ['phone_code' =>'1 868' , 'title' => 'Trinidad and Tobago'],
            ['phone_code' =>'216' , 'title' => 'Tunisia'],
            ['phone_code' =>'90' , 'title' => 'Turkey'],
            ['phone_code' =>'993' , 'title' => 'Turkmenistan'],
            ['phone_code' =>'688' , 'title' => 'Tuvalu (Ellice Islands)'],
            ['phone_code' =>'256' , 'title' => 'Uganda'],
            ['phone_code' =>'380' , 'title' => 'Ukraine'],
            ['phone_code' =>'971' , 'title' => 'United Arab Emirates'],
            ['phone_code' =>'44' , 'title' => 'United Kingdom'],
            ['phone_code' =>'598' , 'title' => 'Uruguay'],
            ['phone_code' =>'1' , 'title' => 'USA'],
            ['phone_code' =>'7' , 'title' => 'Uzbekistan'],
            ['phone_code' =>'678' , 'title' => 'Vanuatu (New Hebrides)'],
            ['phone_code' =>'39' , 'title' => 'Vatican City'],
            ['phone_code' =>'58' , 'title' => 'Venezuela'],
            ['phone_code' =>'84' , 'title' => 'Viet Nam'],
            ['phone_code' =>'1 340' , 'title' => 'Virgin Islands'],
            ['phone_code' =>'681' , 'title' => 'Wallis and Futuna'],
            ['phone_code' =>'685' , 'title' => 'Western Samoa'],
            ['phone_code' =>'381' , 'title' => 'Yemen (People\'s Democratic Republic of)'],
            ['phone_code' =>'967' , 'title' => 'Yemen Arab Republic (North Yemen)'],
            ['phone_code' =>'243' , 'title' => 'Zaire'],
            ['phone_code' =>'260' , 'title' => 'Zambia'],
            ['phone_code' =>'263' , 'title' => 'Zimbabwe']
        ]);

    }
}
